//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTaskAcmService.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.JetNavSMSSoap")]
    public interface JetNavSMSSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/createProg", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        eTaskAcmService.ServiceReference.AdProg createProg(eTaskAcmService.ServiceReference.authenUser authen, eTaskAcmService.ServiceReference.AdProg tmpProg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/createProg", ReplyAction="*")]
        System.Threading.Tasks.Task<eTaskAcmService.ServiceReference.AdProg> createProgAsync(eTaskAcmService.ServiceReference.authenUser authen, eTaskAcmService.ServiceReference.AdProg tmpProg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateProg", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        eTaskAcmService.ServiceReference.AdProg updateProg(eTaskAcmService.ServiceReference.authenUser authen, eTaskAcmService.ServiceReference.AdProg tmpProg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateProg", ReplyAction="*")]
        System.Threading.Tasks.Task<eTaskAcmService.ServiceReference.AdProg> updateProgAsync(eTaskAcmService.ServiceReference.authenUser authen, eTaskAcmService.ServiceReference.AdProg tmpProg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteProg", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int deleteProg(eTaskAcmService.ServiceReference.authenUser authen, string progCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteProg", ReplyAction="*")]
        System.Threading.Tasks.Task<int> deleteProgAsync(eTaskAcmService.ServiceReference.authenUser authen, string progCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/uploadMsisdns", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int uploadMsisdns(eTaskAcmService.ServiceReference.authenUser authen, string progCode, string[] msisdns);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/uploadMsisdns", ReplyAction="*")]
        System.Threading.Tasks.Task<int> uploadMsisdnsAsync(eTaskAcmService.ServiceReference.authenUser authen, string progCode, string[] msisdns);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getDailyProgReport", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        eTaskAcmService.ServiceReference.progReport getDailyProgReport(eTaskAcmService.ServiceReference.authenUser authen, string catCode, string fromDate, string toDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getDailyProgReport", ReplyAction="*")]
        System.Threading.Tasks.Task<eTaskAcmService.ServiceReference.progReport> getDailyProgReportAsync(eTaskAcmService.ServiceReference.authenUser authen, string catCode, string fromDate, string toDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getDailySmsReport", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        eTaskAcmService.ServiceReference.smsReport getDailySmsReport(eTaskAcmService.ServiceReference.authenUser authen, string progCode, string catCode, string fromDate, string toDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getDailySmsReport", ReplyAction="*")]
        System.Threading.Tasks.Task<eTaskAcmService.ServiceReference.smsReport> getDailySmsReportAsync(eTaskAcmService.ServiceReference.authenUser authen, string progCode, string catCode, string fromDate, string toDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getMonthProgReport", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        eTaskAcmService.ServiceReference.progReport getMonthProgReport(eTaskAcmService.ServiceReference.authenUser authen, string catCode, string month);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getMonthProgReport", ReplyAction="*")]
        System.Threading.Tasks.Task<eTaskAcmService.ServiceReference.progReport> getMonthProgReportAsync(eTaskAcmService.ServiceReference.authenUser authen, string catCode, string month);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getMonthSmsReport", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        eTaskAcmService.ServiceReference.smsReport getMonthSmsReport(eTaskAcmService.ServiceReference.authenUser authen, string progCode, string catCode, string month);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getMonthSmsReport", ReplyAction="*")]
        System.Threading.Tasks.Task<eTaskAcmService.ServiceReference.smsReport> getMonthSmsReportAsync(eTaskAcmService.ServiceReference.authenUser authen, string progCode, string catCode, string month);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getYearProgReport", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        eTaskAcmService.ServiceReference.progReport getYearProgReport(eTaskAcmService.ServiceReference.authenUser authen, string catCode, string year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getYearProgReport", ReplyAction="*")]
        System.Threading.Tasks.Task<eTaskAcmService.ServiceReference.progReport> getYearProgReportAsync(eTaskAcmService.ServiceReference.authenUser authen, string catCode, string year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getYearSmsReport", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        eTaskAcmService.ServiceReference.smsReport getYearSmsReport(eTaskAcmService.ServiceReference.authenUser authen, string progCode, string catCode, string year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getYearSmsReport", ReplyAction="*")]
        System.Threading.Tasks.Task<eTaskAcmService.ServiceReference.smsReport> getYearSmsReportAsync(eTaskAcmService.ServiceReference.authenUser authen, string progCode, string catCode, string year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int SendMT(string dest, string name, string msgBody, string contentType, string serviceID, long mtID, string cpID, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMT", ReplyAction="*")]
        System.Threading.Tasks.Task<int> SendMTAsync(string dest, string name, string msgBody, string contentType, string serviceID, long mtID, string cpID, string username, string password);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class authenUser : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int isAdminField;
        
        private string cpCodeField;
        
        private string nameField;
        
        private string passField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int isAdmin {
            get {
                return this.isAdminField;
            }
            set {
                this.isAdminField = value;
                this.RaisePropertyChanged("isAdmin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string cpCode {
            get {
                return this.cpCodeField;
            }
            set {
                this.cpCodeField = value;
                this.RaisePropertyChanged("cpCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string pass {
            get {
                return this.passField;
            }
            set {
                this.passField = value;
                this.RaisePropertyChanged("pass");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class smsRecord : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string dateField;
        
        private int moReplyField;
        
        private int mt1ErrorField;
        
        private int mt1NotSendField;
        
        private int mt1SuccessField;
        
        private int mt2SuccessField;
        
        private int numOderField;
        
        private int sms1SuccessField;
        
        private int sms2SuccessField;
        
        private int subUnRegField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int moReply {
            get {
                return this.moReplyField;
            }
            set {
                this.moReplyField = value;
                this.RaisePropertyChanged("moReply");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int mt1Error {
            get {
                return this.mt1ErrorField;
            }
            set {
                this.mt1ErrorField = value;
                this.RaisePropertyChanged("mt1Error");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int mt1NotSend {
            get {
                return this.mt1NotSendField;
            }
            set {
                this.mt1NotSendField = value;
                this.RaisePropertyChanged("mt1NotSend");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int mt1Success {
            get {
                return this.mt1SuccessField;
            }
            set {
                this.mt1SuccessField = value;
                this.RaisePropertyChanged("mt1Success");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int mt2Success {
            get {
                return this.mt2SuccessField;
            }
            set {
                this.mt2SuccessField = value;
                this.RaisePropertyChanged("mt2Success");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int numOder {
            get {
                return this.numOderField;
            }
            set {
                this.numOderField = value;
                this.RaisePropertyChanged("numOder");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int sms1Success {
            get {
                return this.sms1SuccessField;
            }
            set {
                this.sms1SuccessField = value;
                this.RaisePropertyChanged("sms1Success");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public int sms2Success {
            get {
                return this.sms2SuccessField;
            }
            set {
                this.sms2SuccessField = value;
                this.RaisePropertyChanged("sms2Success");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public int subUnReg {
            get {
                return this.subUnRegField;
            }
            set {
                this.subUnRegField = value;
                this.RaisePropertyChanged("subUnReg");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class smsReport : object, System.ComponentModel.INotifyPropertyChanged {
        
        private smsRecord[] smsRecordsField;
        
        private int statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("smsRecords", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public smsRecord[] smsRecords {
            get {
                return this.smsRecordsField;
            }
            set {
                this.smsRecordsField = value;
                this.RaisePropertyChanged("smsRecords");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class progSmsRecord : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string dateField;
        
        private int mt1SuccessField;
        
        private int mt2SuccessField;
        
        private int progCompleteField;
        
        private int progCreateField;
        
        private int progFinishField;
        
        private int sms1SuccessField;
        
        private int sms2SuccessField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int mt1Success {
            get {
                return this.mt1SuccessField;
            }
            set {
                this.mt1SuccessField = value;
                this.RaisePropertyChanged("mt1Success");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int mt2Success {
            get {
                return this.mt2SuccessField;
            }
            set {
                this.mt2SuccessField = value;
                this.RaisePropertyChanged("mt2Success");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int progComplete {
            get {
                return this.progCompleteField;
            }
            set {
                this.progCompleteField = value;
                this.RaisePropertyChanged("progComplete");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int progCreate {
            get {
                return this.progCreateField;
            }
            set {
                this.progCreateField = value;
                this.RaisePropertyChanged("progCreate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int progFinish {
            get {
                return this.progFinishField;
            }
            set {
                this.progFinishField = value;
                this.RaisePropertyChanged("progFinish");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int sms1Success {
            get {
                return this.sms1SuccessField;
            }
            set {
                this.sms1SuccessField = value;
                this.RaisePropertyChanged("sms1Success");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int sms2Success {
            get {
                return this.sms2SuccessField;
            }
            set {
                this.sms2SuccessField = value;
                this.RaisePropertyChanged("sms2Success");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class progReport : object, System.ComponentModel.INotifyPropertyChanged {
        
        private progSmsRecord[] progSmsRecordsField;
        
        private int statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("progSmsRecords", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public progSmsRecord[] progSmsRecords {
            get {
                return this.progSmsRecordsField;
            }
            set {
                this.progSmsRecordsField = value;
                this.RaisePropertyChanged("progSmsRecords");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AdProg : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string progCodeField;
        
        private string categoryField;
        
        private string contentField;
        
        private string sentStartDateField;
        
        private string sentFinishDateField;
        
        private int maxSmsField;
        
        private string aliasField;
        
        private string sentScheduleField;
        
        private string exceptionDayField;
        
        private int sentTimeZoneField;
        
        private string createdUserField;
        
        private string createdDateField;
        
        private int priorityField;
        
        private int statusField;
        
        private int sentTypeField;
        
        private string zoneListField;
        
        private string catListField;
        
        private int totalSubField;
        
        private int genderField;
        
        private int minYearField;
        
        private int maxYearField;
        
        private int jobField;
        
        private int incomeField;
        
        private int processStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string progCode {
            get {
                return this.progCodeField;
            }
            set {
                this.progCodeField = value;
                this.RaisePropertyChanged("progCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
                this.RaisePropertyChanged("category");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
                this.RaisePropertyChanged("content");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string sentStartDate {
            get {
                return this.sentStartDateField;
            }
            set {
                this.sentStartDateField = value;
                this.RaisePropertyChanged("sentStartDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string sentFinishDate {
            get {
                return this.sentFinishDateField;
            }
            set {
                this.sentFinishDateField = value;
                this.RaisePropertyChanged("sentFinishDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int maxSms {
            get {
                return this.maxSmsField;
            }
            set {
                this.maxSmsField = value;
                this.RaisePropertyChanged("maxSms");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string alias {
            get {
                return this.aliasField;
            }
            set {
                this.aliasField = value;
                this.RaisePropertyChanged("alias");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string sentSchedule {
            get {
                return this.sentScheduleField;
            }
            set {
                this.sentScheduleField = value;
                this.RaisePropertyChanged("sentSchedule");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string exceptionDay {
            get {
                return this.exceptionDayField;
            }
            set {
                this.exceptionDayField = value;
                this.RaisePropertyChanged("exceptionDay");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public int sentTimeZone {
            get {
                return this.sentTimeZoneField;
            }
            set {
                this.sentTimeZoneField = value;
                this.RaisePropertyChanged("sentTimeZone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string createdUser {
            get {
                return this.createdUserField;
            }
            set {
                this.createdUserField = value;
                this.RaisePropertyChanged("createdUser");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string createdDate {
            get {
                return this.createdDateField;
            }
            set {
                this.createdDateField = value;
                this.RaisePropertyChanged("createdDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public int priority {
            get {
                return this.priorityField;
            }
            set {
                this.priorityField = value;
                this.RaisePropertyChanged("priority");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public int sentType {
            get {
                return this.sentTypeField;
            }
            set {
                this.sentTypeField = value;
                this.RaisePropertyChanged("sentType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string zoneList {
            get {
                return this.zoneListField;
            }
            set {
                this.zoneListField = value;
                this.RaisePropertyChanged("zoneList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string catList {
            get {
                return this.catListField;
            }
            set {
                this.catListField = value;
                this.RaisePropertyChanged("catList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public int totalSub {
            get {
                return this.totalSubField;
            }
            set {
                this.totalSubField = value;
                this.RaisePropertyChanged("totalSub");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public int gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
                this.RaisePropertyChanged("gender");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public int minYear {
            get {
                return this.minYearField;
            }
            set {
                this.minYearField = value;
                this.RaisePropertyChanged("minYear");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public int maxYear {
            get {
                return this.maxYearField;
            }
            set {
                this.maxYearField = value;
                this.RaisePropertyChanged("maxYear");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public int job {
            get {
                return this.jobField;
            }
            set {
                this.jobField = value;
                this.RaisePropertyChanged("job");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public int income {
            get {
                return this.incomeField;
            }
            set {
                this.incomeField = value;
                this.RaisePropertyChanged("income");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public int processStatus {
            get {
                return this.processStatusField;
            }
            set {
                this.processStatusField = value;
                this.RaisePropertyChanged("processStatus");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface JetNavSMSSoapChannel : eTaskAcmService.ServiceReference.JetNavSMSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class JetNavSMSSoapClient : System.ServiceModel.ClientBase<eTaskAcmService.ServiceReference.JetNavSMSSoap>, eTaskAcmService.ServiceReference.JetNavSMSSoap {
        
        public JetNavSMSSoapClient() {
        }
        
        public JetNavSMSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JetNavSMSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JetNavSMSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JetNavSMSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public eTaskAcmService.ServiceReference.AdProg createProg(eTaskAcmService.ServiceReference.authenUser authen, eTaskAcmService.ServiceReference.AdProg tmpProg) {
            return base.Channel.createProg(authen, tmpProg);
        }
        
        public System.Threading.Tasks.Task<eTaskAcmService.ServiceReference.AdProg> createProgAsync(eTaskAcmService.ServiceReference.authenUser authen, eTaskAcmService.ServiceReference.AdProg tmpProg) {
            return base.Channel.createProgAsync(authen, tmpProg);
        }
        
        public eTaskAcmService.ServiceReference.AdProg updateProg(eTaskAcmService.ServiceReference.authenUser authen, eTaskAcmService.ServiceReference.AdProg tmpProg) {
            return base.Channel.updateProg(authen, tmpProg);
        }
        
        public System.Threading.Tasks.Task<eTaskAcmService.ServiceReference.AdProg> updateProgAsync(eTaskAcmService.ServiceReference.authenUser authen, eTaskAcmService.ServiceReference.AdProg tmpProg) {
            return base.Channel.updateProgAsync(authen, tmpProg);
        }
        
        public int deleteProg(eTaskAcmService.ServiceReference.authenUser authen, string progCode) {
            return base.Channel.deleteProg(authen, progCode);
        }
        
        public System.Threading.Tasks.Task<int> deleteProgAsync(eTaskAcmService.ServiceReference.authenUser authen, string progCode) {
            return base.Channel.deleteProgAsync(authen, progCode);
        }
        
        public int uploadMsisdns(eTaskAcmService.ServiceReference.authenUser authen, string progCode, string[] msisdns) {
            return base.Channel.uploadMsisdns(authen, progCode, msisdns);
        }
        
        public System.Threading.Tasks.Task<int> uploadMsisdnsAsync(eTaskAcmService.ServiceReference.authenUser authen, string progCode, string[] msisdns) {
            return base.Channel.uploadMsisdnsAsync(authen, progCode, msisdns);
        }
        
        public eTaskAcmService.ServiceReference.progReport getDailyProgReport(eTaskAcmService.ServiceReference.authenUser authen, string catCode, string fromDate, string toDate) {
            return base.Channel.getDailyProgReport(authen, catCode, fromDate, toDate);
        }
        
        public System.Threading.Tasks.Task<eTaskAcmService.ServiceReference.progReport> getDailyProgReportAsync(eTaskAcmService.ServiceReference.authenUser authen, string catCode, string fromDate, string toDate) {
            return base.Channel.getDailyProgReportAsync(authen, catCode, fromDate, toDate);
        }
        
        public eTaskAcmService.ServiceReference.smsReport getDailySmsReport(eTaskAcmService.ServiceReference.authenUser authen, string progCode, string catCode, string fromDate, string toDate) {
            return base.Channel.getDailySmsReport(authen, progCode, catCode, fromDate, toDate);
        }
        
        public System.Threading.Tasks.Task<eTaskAcmService.ServiceReference.smsReport> getDailySmsReportAsync(eTaskAcmService.ServiceReference.authenUser authen, string progCode, string catCode, string fromDate, string toDate) {
            return base.Channel.getDailySmsReportAsync(authen, progCode, catCode, fromDate, toDate);
        }
        
        public eTaskAcmService.ServiceReference.progReport getMonthProgReport(eTaskAcmService.ServiceReference.authenUser authen, string catCode, string month) {
            return base.Channel.getMonthProgReport(authen, catCode, month);
        }
        
        public System.Threading.Tasks.Task<eTaskAcmService.ServiceReference.progReport> getMonthProgReportAsync(eTaskAcmService.ServiceReference.authenUser authen, string catCode, string month) {
            return base.Channel.getMonthProgReportAsync(authen, catCode, month);
        }
        
        public eTaskAcmService.ServiceReference.smsReport getMonthSmsReport(eTaskAcmService.ServiceReference.authenUser authen, string progCode, string catCode, string month) {
            return base.Channel.getMonthSmsReport(authen, progCode, catCode, month);
        }
        
        public System.Threading.Tasks.Task<eTaskAcmService.ServiceReference.smsReport> getMonthSmsReportAsync(eTaskAcmService.ServiceReference.authenUser authen, string progCode, string catCode, string month) {
            return base.Channel.getMonthSmsReportAsync(authen, progCode, catCode, month);
        }
        
        public eTaskAcmService.ServiceReference.progReport getYearProgReport(eTaskAcmService.ServiceReference.authenUser authen, string catCode, string year) {
            return base.Channel.getYearProgReport(authen, catCode, year);
        }
        
        public System.Threading.Tasks.Task<eTaskAcmService.ServiceReference.progReport> getYearProgReportAsync(eTaskAcmService.ServiceReference.authenUser authen, string catCode, string year) {
            return base.Channel.getYearProgReportAsync(authen, catCode, year);
        }
        
        public eTaskAcmService.ServiceReference.smsReport getYearSmsReport(eTaskAcmService.ServiceReference.authenUser authen, string progCode, string catCode, string year) {
            return base.Channel.getYearSmsReport(authen, progCode, catCode, year);
        }
        
        public System.Threading.Tasks.Task<eTaskAcmService.ServiceReference.smsReport> getYearSmsReportAsync(eTaskAcmService.ServiceReference.authenUser authen, string progCode, string catCode, string year) {
            return base.Channel.getYearSmsReportAsync(authen, progCode, catCode, year);
        }
        
        public int SendMT(string dest, string name, string msgBody, string contentType, string serviceID, long mtID, string cpID, string username, string password) {
            return base.Channel.SendMT(dest, name, msgBody, contentType, serviceID, mtID, cpID, username, password);
        }
        
        public System.Threading.Tasks.Task<int> SendMTAsync(string dest, string name, string msgBody, string contentType, string serviceID, long mtID, string cpID, string username, string password) {
            return base.Channel.SendMTAsync(dest, name, msgBody, contentType, serviceID, mtID, cpID, username, password);
        }
    }
}
